### ISSUE TITLE
KMinion topic check fails if topic does not exist

### ISSUE THREAD

**Issue by weeco** [cloudhut/kminion#114]
Hi I tried with the latest version: master-1e3a1d5. I got the following issue with the last message repeating. The Errors after "Starting to consume end to end topic" appeared after 15 min.

![image](https://user-images.githubusercontent.com/90798747/133500388-1ff02859-9a9d-47a0-897b-14d2b215e24b.png)

_Originally posted by @JordnL in https://github.com/cloudhut/kminion/issues/112#issuecomment-920334498_

**Comment by rmb938** [comment]
@weeco Just to comment on your reply. 

> You can temporarily fix this by either creating the topic on your own - or enabling the topic creation. Basically the problem there is just that a proper error code is not printed. The topic simply does not exist and the kminion configuration says that KMinion is not allowed to create that topic apparently.

Topic creation flag is enabled. We are also giving Kafka Minion (for this test) super user credentials for Kafka so it should have access to create the topic, but it never does and then prints the error above.

**Comment by weeco** [comment]
@rmb938 Could you check whether this issue is still existent in the latest version? This code portion has been kind of rewritten and successfully tested in multiple setups and configurations nowadays.
