### ISSUE TITLE
kminion_kafka_consumer_group_topic_lag metrics are not shown up in latest version

### ISSUE THREAD

**Issue by Avani231194** [cloudhut/kminion#117]
kminion_kafka_consumer_group_topic_lag metrics are not shown up in latest version.

**Comment by Avani231194** [comment]
Temp Resolution:  works well on v2.0.0

**Comment by weeco** [comment]
@Avani231194 I'm not able to reproduce this. Are you using `scrapeMode: offsetsTopic` and haven't awaited that the offsets topic has been fully consumed by any chance?
