### ISSUE TITLE
Commit count metrics missing

### ISSUE THREAD

**Issue by punit-kulal** [cloudhut/kminion#136]
I am using the v2.2.0 of kminion to monitor my kafka cluster.
The scrapeMode is set to adminAPI.
`kminion_kafka_consumer_group_offset_commits_total` metric is not exported by the kminion deployment.
Is this metric only exposed in `offsetsTopic` mode. If yes, adding that note in the doc would be helpful.

**Comment by weeco** [comment]
Hi @punit-kulal ,
your assumption is correct and it is documented in the reference config / docs here: https://github.com/cloudhut/kminion/blob/05a03ed6175352f8e4a9e99d32589bb7bc163dc2/docs/reference-config.yaml#L60-L68
