### ISSUE TITLE
Add consumer group member count

### ISSUE THREAD

**Issue by godwhoa** [cloudhut/kminion#18]
Currently in the process of moving from kafka_exporter to kafka-minion only metric that we are missing is the [consumer group member count](https://github.com/danielqsj/kafka_exporter/commit/1c176efeb63b5107680783faa0d8133a87249a3f).
Already have a working prototype for this, if there are no objections I would like to make a PR.

**Comment by weeco** [comment]
Hey, a PR for this is welcome. Thank you for the effort and asking beforehand!

**Comment by tkdrahn** [comment]
subscribed - would like this metric as well

**Comment by weeco** [comment]
`member_count` is now a label of the new metric `consumer_group_info` (v2+).
