### ISSUE TITLE
Standalone Setup on NON-Docker server

### ISSUE THREAD

**Issue by Kumartg** [cloudhut/kminion#36]
Hi Team,
Can you please share a detailed steps to install "kafka-minion" project on non-docker server?
I am planning to use this project to export Kafka metrics to prometheus and use grafana for monitoring. 

It would be great if you share it at earliest.

**Comment by godwhoa** [comment]
* [Install Go](https://golang.org/doc/install)
* `git clone https://github.com/cloudworkz/kafka-minion && cd kafka-minion`
* `CGO_ENABLED=0 go build`

Once you have the compiled binary you can run it like any another Linux program, you configure it using environment variables(refer to README)

Here's my systemd unit file:
```
[Unit]
Description=Prometheus Kafka Minion
After=network-online.target

[Service]
Type=simple
User=kafka-minion
Group=kafka-minion
Environment=TELEMETRY_PORT=9999
Environment=KAFKA_BROKERS=YOUR_BROKER_HERE:9092
Environment=VERSION=1.0.0
ExecStart=/usr/local/bin/kafka-minion
SyslogIdentifier=kafka_minion
Restart=always

PrivateTmp=yes
ProtectHome=yes
NoNewPrivileges=yes

ProtectSystem=strict
ProtectControlGroups=true
ProtectKernelModules=true
ProtectKernelTunables=yes

[Install]
WantedBy=multi-user.target
```

**Comment by weeco** [comment]
You are supposed to cimpile the binary on your own (as described by @godwhoa) because we don't release/upload binaries as of now (feel free to submit an issue for that though). Now that we have GitHub actions this should be quite easy to do.

**Comment by Kumartg** [comment]
Hi Team,
Thanks for your quick response. I have followed your above steps and getting below error :
Any thoughts?

$ CGO_ENABLED=0 go build
go: github.com/DataDog/zstd@v1.4.4: Get "https://proxy.golang.org/github.com/%21data%21dog/zstd/@v/v1.4.4.mod": proxyconnect tcp: tls: first record does not look like a TLS handshake

**Comment by Kumartg** [comment]
Hi,
Please ignore above comment , i am able to build "kafka-minion" and able to integrate with prometheus. I am getting only below metrics for kafka consumer .  Where can i find additional kafka metrics for consumer offsets?

-- prometheus metrics

net_conntrack_dialer_conn_attempted_total{dialer_name="kafka-minion-222"} 36
net_conntrack_dialer_conn_closed_total{dialer_name="kafka-minion-222"} 1
net_conntrack_dialer_conn_established_total{dialer_name="kafka-minion-222"} 2
net_conntrack_dialer_conn_failed_total{dialer_name="kafka-minion-222",reason="refused"} 34
net_conntrack_dialer_conn_failed_total{dialer_name="kafka-minion-222",reason="resolution"} 0
net_conntrack_dialer_conn_failed_total{dialer_name="kafka-minion-222",reason="timeout"} 0
net_conntrack_dialer_conn_failed_total{dialer_name="kafka-minion-222",reason="unknown"} 34
prometheus_target_scrape_pool_sync_total{scrape_job="kafka-minion-222"} 1
prometheus_target_sync_length_seconds{scrape_job="kafka-minion-222",quantile="0.01"} 3.5452e-05
prometheus_target_sync_length_seconds{scrape_job="kafka-minion-222",quantile="0.05"} 3.5452e-05
prometheus_target_sync_length_seconds{scrape_job="kafka-minion-222",quantile="0.5"} 3.5452e-05
prometheus_target_sync_length_seconds{scrape_job="kafka-minion-222",quantile="0.9"} 3.5452e-05
prometheus_target_sync_length_seconds{scrape_job="kafka-minion-222",quantile="0.99"} 3.5452e-05
prometheus_target_sync_length_seconds_sum{scrape_job="kafka-minion-222"} 3.5452e-05
prometheus_target_sync_length_seconds_count{scrape_job="kafka-minion-222"} 1

### /var/log/messages

Mar 13 04:23:25 "hostname" systemd: Started Prometheus Kafka Minion.
Mar 13 04:23:25 "hostname" systemd: Starting Prometheus Kafka Minion...
Mar 13 04:23:25 "hostname" kafka_minion: {"level":"info","msg":"Starting kafka minion version1.0.0","time":"2020-03-13T04:23:25-07:00"}
Mar 13 04:23:25 "hostname" kafka_minion: {"address":"1.1.1.1:9868,1.1.1.2:9868","level":"info","module":"cluster","msg":"connecting to kafka cluster","time":"2020-03-13T04:23:25-07:00"}
Mar 13 04:23:25 "hostname" kafka_minion: {"address":"1.1.1.1:9868,1.1.1.2:9868","level":"info","module":"cluster","msg":"successfully connected to kafka cluster","time":"2020-03-13T04:23:25-07:00"}
Mar 13 04:23:25 "hostname" kafka_minion: {"address":"1.1.1.1:9868,1.1.1.2:9868","level":"info","module":"offset_consumer","msg":"Connecting to kafka cluster","time":"2020-03-13T04:23:25-07:00"}
Mar 13 04:23:25 "hostname" kafka_minion: {"address":"1.1.1.1:9868,1.1.1.2:9868","level":"info","module":"offset_consumer","msg":"Successfully connected to kafka cluster","time":"2020-03-13T04:23:25-07:00"}
Mar 13 04:23:25 "hostname" kafka_minion: {"count":50,"level":"info","msg":"Starting '50' partition consumers","time":"2020-03-13T04:23:25-07:00","topic":"__consumer_offsets"}
Mar 13 04:23:25 "hostname" kafka_minion: {"count":50,"level":"info","msg":"Spawned all consumers","time":"2020-03-13T04:23:25-07:00","topic":"__consumer_offsets"}
Mar 13 04:23:25 "hostname" kafka_minion: {"level":"info","msg":"Listening on: '0.0.0.0:9999","time":"2020-03-13T04:23:25-07:00"}
Mar 13 04:23:25 "hostname" kafka_minion: {"level":"info","module":"storage","msg":"Registered 50 __consumer_offsets partitions which have to be consumed before metrics can be exposed","time":"2020-03-13T04:23:25-07:00"}

**Comment by weeco** [comment]
As the last log message described Kafka Minion first has to process all partitions which contain the consumer offsets. This should take roughly 1-10 minutes depending on the number of consumer offsets and the available resources/throughput Kafka Minion has.

If this takes longer or you suspect an issue with that please turn on debug logs. There's an issue which has been reported by a few users that Kafka Minion never finishes to consume the metrics initially. Maybe you are experiencing the same problem? Unfortunately I haven't figured out what's the reason for this as the logic seems to be fine and I am not able to reproduce this in any of my kafka clusters.

**Comment by weeco** [comment]
Binaries have been added, see: https://github.com/cloudhut/kminion/releases/tag/v2.0.0
