### ISSUE TITLE
Need topic level summary metrics

### ISSUE THREAD

**Issue by kaushal1562** [cloudhut/kminion#42]
Can we get the topic summary metrics as well in addition to the existing metrics.

Getting consumer group current offset, and low and high watermark at topic level would be  great feature to add on.

Thanks,

Kaushal

**Comment by weeco** [comment]
I am not sure if I understand your issue. There's no such thing like a group offset on a topic level?
All offsets/watermarks and lags are calculated on a per partition basis. How would it help to sum all topic partitions' low or high watermarks?

**Comment by wulfuric** [comment]
This is something I would be interested in as well, a bit more background is that on clusters with a lot of partitions, 10k+ some of the topics having 500 partitions, scraping all of these metrics at the partition level has a heavy toll on the prometheus server doing the scraping.

Although I understand these metrics aren't emitted at the topic level, it would be helpful to have topic level metrics summarized.

````
kafka_minion_topic_partition_high_water_mark{topic, partition} 
kafka_minion_topic_partition_low_water_mark{topic, partition} 
kafka_minion_topic_partition_message_count{topic, partition}
```
Could all be summed across partitions at the topic level in the exporter itself, and then either a flag could be added to determine whether someone wants partition level, or topic level metrics emitted, or even without that as long as the summary metrics existed clients could do a metric relabel with a `keep` or `drop`, to take the metrics they want.

I'm not very familiar with go, but likely need to dive in soon, but I think for larger clusters this functionality would be quite nice. Although in a large cluster I potentially would skip scraping message count, and compute that on the prometheus end.

**Comment by weeco** [comment]
> This is something I would be interested in as well, a bit more background is that on clusters with a lot of partitions, 10k+ some of the topics having 500 partitions, scraping all of these metrics at the partition level has a heavy toll on the prometheus server doing the scraping.

Agreed, this can potentially cause problems for Prometheus! Just adding more metrics as this issues suggests doesn't fix this though.

> and then either a flag could be added to determine whether someone wants partition level, or topic level metrics emitted

Makes sense to me. I am not sure whether it should be done exactly like that or if there could be more elloborated config settings. 

I am not sure whether @kaushal1562 intentions align with @wulfuric wishes? Until we figure out, could you (@wulfuric ) create a separate issue for that?

**Comment by kaushal1562** [comment]
@weeco , I am looking for the same details which @wulfuric added.  Both requirements are aligned.

**Comment by wulfuric** [comment]
Agreed, I think this would have a lot of value but the implementation of it is tricky.

You're right, if topic summary metrics are added this will lead to more time series metrics each scrape.  This would be the simplest on the exporter end, but it would push the burden to the customer, they could include in their prometheus scrape a list of metrics they do want to scrape.
```
metric_relabel_configs:
--
 - source_labels: [__name__]
    separator: ;
    regex: kafka_minion_topic_log_dir_size|kafka_minion_topic_topic_low_water_mark|kafka_minion_topic_topic_high_water_mark
    replacement: $1
    action: keep
```

Otherwise the exporter could be configured with flags, potentially a boolean flag for `TOPIC_SUMMARY_METRICS`, and `PARTITION_LEVEL_METRICS`, I could see cases where someone could want both enabled, which would give you the granularity of partition level metrics for deeper debugging but quicker queries with summary level metrics without needing to sum at the prometheus level.

**Comment by weeco** [comment]
I implemented that feature in v2 and the "granularity" is now configurable, see: https://github.com/cloudhut/kminion/blob/753af5610f21c576ee0fec71bb5280456d2e4439/docs/reference-config.yaml#L57

**Comment by wulfuric** [comment]
This looks awesome, excited to try it out thank you!

**Comment by weeco** [comment]
V2 is basically ready to use. I'll close this issue :)
