### ISSUE TITLE
Mismatch in the message count 

### ISSUE THREAD

**Issue by guda249** [cloudhut/kminion#56]
Hi, 
Firstly thank you !! for the handy tool for monitoring the Kafka consumers. :)

I see there is huge mismatch in the message count on the topic with compact policy .
Scenario:
There are certain change-log topics created by Kafka streams applications ; below are the properties set on the topic:
PartitionCount: 4
ReplicationFactor: 3
Configs: cleanup.policy=compact,segment.bytes=1073741824,retention.ms=7200000,unclean.leader.election.enable=true.

The Kafka minion is reporting the number of messages on that topic as 12Bil+ ; where the disk size for that topic is never crossed from 1Gb. (Confirmed via kafka jmx metric kafka_log_size).

Can you point out to; i'm missing something.

Thanks

**Comment by weeco** [comment]
Hi @guda249 ,
you are right - for compact topics the reported number of messages can be very wrong. The description of this metric series in the readme:

> Number of messages for a given partition. Calculated by subtracting high water mark by low water mark. Thus this metric is likely to be invalid for compacting topics, but it still can be helpful to get an idea about the number of messages in that topic.

We intend to report better estimations in [Kowl](https://github.com/cloudhut/kowl) which is an opensource Kafka Web UI. I just submitted my idea how we can do that in https://github.com/cloudhut/kowl/issues/83 . I am not sure whether this should also be ported into Kafka Minion once we agreed on a decent approach.

**Comment by guda249** [comment]
Hi @weeco , idea seems good 👍 ; but the real problem is in deciding number of messages to read; and how approx the count will be ;

**Comment by weeco** [comment]
It turned out that isn't as easy as presumed due to compression and batching of records. The metric is no longer exposed as message count either anymore. So the best we can get for now is a delta between the high and low watermark for each partition unless Kafka provides a better API to access the number of messages in a partition.
