### ISSUE TITLE
How do I execute kafka-minion in normal environment （no docker）

### ISSUE THREAD

**Issue by ZSH9053** [cloudhut/kminion#57]
[root@jy-kafka-01 kafka-minion]# ./kafka-minion --VERSION=1.0.1
{"level":"fatal","msg":"Error parsing env vars into opts. required key VERSION missing value","time":"2020-07-30T17:19:36+08:00"}
[root@jy-kafka-01 kafka-minion]# ./kafka-minion --version=1.0.1
{"level":"fatal","msg":"Error parsing env vars into opts. required key VERSION missing value","time":"2020-07-30T17:19:42+08:00"}
[root@jy-kafka-01 kafka-minion]# ./kafka-minion version=1.0.1
{"level":"fatal","msg":"Error parsing env vars into opts. required key VERSION missing value","time":"2020-07-30T17:19:48+08:00"}

**Comment by ZSH9053** [comment]
@weeco

**Comment by hdhoang** [comment]
I do `export VERSION=1.0.1-x-g...commit...` before-hand. But I think this should be inside the binary somehow, not only in docker env

**Comment by weeco** [comment]
The binary expects a `VERSION` env to be set. However this has changed in V2 where it is optional. Sorry for not responding earlier.
