### ISSUE TITLE
Add consumer groups GroupState and ProtocolType metrics

### ISSUE THREAD

**Issue by amuraru** [cloudhut/kminion#58]
Kafka offers [ListGroups](https://kafka.apache.org/protocol.html#The_Messages_ListGroups) and [DescribeGroups](https://kafka.apache.org/protocol.html#The_Messages_DescribeGroups) APIs that can be used to also expose the `state` and `type` for a given consumer group.

**Comment by weeco** [comment]
Both have been added in V2 :-)
