### ISSUE TITLE
Using kafka minion side by side with jmx exporter

### ISSUE THREAD

**Issue by meelmeal** [cloudhut/kminion#59]
Hi,
I have a test environment with a 3-node Kafka (Confluent Kafka) running JMX exporter and kafka minion together.

On the prometheus side , I have tried defining all 6 targets (3 x jmx and 3 x minion) together in the same job or in different jobs but in either way, Grafana dashboards either don't pick up the metrics or combine them and show me 6 brokers instead of 3.

Is there a specific way to define the Prometheus scrape jobs so that both jmx exporter and kafka minion can run side by side without colliding with eachother ?

**Comment by weeco** [comment]
You need to make sure that each services gets it's own prometheus label attached (in your prometheus job config). This way they can't collide.
