### ISSUE TITLE
kafka_minion_group_topic_partition_last_commit returning current time

### ISSUE THREAD

**Issue by 46Wil** [cloudhut/kminion#60]
We are trying to use kafka_minion_group_topic_partition_last_commit to return the last commit time for a given group topic.  We are trying this with 5 different ones and they all appear to give the current time.  I don't see any other posts with the same issue so I wonder if it is an issue with our setup, but don't have any good examples to compare to.  We are running Grafana 7.0.3.  Any insights into what could be causing this, or example snipets of how to setup a panel to correctly display this would be highly appreciated.

**Comment by weeco** [comment]
Hmm I think there was actually a bug with this but I can't recall anymore. Are you using the latest version?

**Comment by 46Wil** [comment]
Grafana: 7.0.3
Prometheus: 2.19.1
kafka-minion: 1.2.0, though that seems counter intuitive since the latest version is 1.0.1...

**Comment by 46Wil** [comment]
I appreciate you calling attention to the version.  We updated kafka-minion to the latest and still no luck.  Any other ideas?

**Comment by weeco** [comment]
Are you checking inactive consumer group offsets? If they are all active it's indeed expected that this will return the current timestamp for all offsets
