### ISSUE TITLE
Pods of kafka minion not coming up.Getting below error .What could be the issue?

### ISSUE THREAD

**Issue by kalpita28** [cloudhut/kminion#61]
{"level":"info","msg":"Starting kafka minion version1.0.0","time":"2020-09-16T08:44:07Z"}
{"level":"panic","msg":"Could not load X509 key pair. %!(EXTRA *errors.errorString=no valid private key found)","time":"2020-09-16T08:44:07Z"}
panic: (*logrus.Entry) (0x94ef00,0xc0000dbdc0)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc000060360, 0xc00006dce0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:239 +0x2ce
github.com/sirupsen/logrus.(*Entry).Log(0xc0000dbab0, 0xc000000000, 0xc000141858, 0x1, 0x1)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:268 +0xed
github.com/sirupsen/logrus.(*Logger).Log(0xc000060360, 0x0, 0xc000141858, 0x1, 0x1)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 +0x7f
github.com/sirupsen/logrus.(*Logger).Panic(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:233
github.com/sirupsen/logrus.Panic(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/exported.go:129
github.com/google-cloud-tools/kafka-minion/kafka.saramaClientConfig(0xc000138000, 0xc0001419b8)
        /app/kafka/connection_helper.go:65 +0x3e3
github.com/google-cloud-tools/kafka-minion/kafka.NewCluster(0xc000138000, 0xc000060ba0, 0xc00005c7c0)
        /app/kafka/cluster.go:74 +0x270
main.main()
        /app/main.go:48 +0x2b6

**Comment by weeco** [comment]
It seems like your TLS private key is wrong (wrong format? wrong filepath? encrypted?...)
