### ISSUE TITLE
Filter at consumer group level

### ISSUE THREAD

**Issue by guda249** [cloudhut/kminion#64]
Hi,

I Would like to request a new feature/improvement. Currently there is an option to filter the topics using 'EXPORTER_TOPIC_FILTER' similarly there could be an option ,'EXPORTER_CONSUMER_FILTER'  to filter consumer based on the multiple regex .

I don't think the 'EXPORTER_TOPIC_FILTER' supports multiple regex separated by comma; 

This would be an definitely useful for teams which uses the shared kafka across the org/multiple teams.

**Comment by Manicben** [comment]
fwiw, this also helps with randomised consumer groups, such as those created by `kafkacat`.
The volume of metrics exposed by Kafka Minion is insane, we'd consider this feature to be essential and it may be why Kafka Minion consumes so much memory to the point where it gets OOMKilled even when given 5GB+.

**Comment by weeco** [comment]
I'm currently working on v2 and I'll add the possibility to specify allowedGroups and ignoredGroups via one or more regex strings. Would that work for you?

```go
type ConsumerGroupConfig struct {
	// AllowedGroups are regex strings of group ids that shall be exported
	AllowedGroupIDs []string `koanf:"allowedGroups"`

	// IgnoredGroups are regex strings of group ids that shall be ignored/skipped when exporting metrics. Ignored groups
	// take precedence over allowed groups.
	IgnoredGroupIDs []string `koanf:"ignoredGroups"`
}
```

**Comment by Manicben** [comment]
Yep, that sounds great. Are there any timelines on v2 by any chance?

**Comment by weeco** [comment]
I aim to have beta version of v2 with a similar feature set ready to be tested next week. Some code is already pushed into the v2 branch

**Comment by weeco** [comment]
V2 is ready to be released / used. I'll close the issue accordingly
