### ISSUE TITLE
Is the kafka_minion_group_topic_partition_expires_at metric wrong?

### ISSUE THREAD

**Issue by frenayj** [cloudhut/kminion#66]
According to the doc the metric `kafka_minion_group_topic_partition_expires_at` should return
> Timestamp when this offset will expire if there won't be further commits

But when I extract the values with Prometheus, the maximum value for partitions being constantly consumed (and produced to) live is always exactly 7 days ago.

As per the code:
https://github.com/cloudworkz/kafka-minion/blob/44f4da3aa18bf0054c28a4a3d756d0e00b233a6c/collector/collector.go#L280

`now() + (-7days)`

I could be wrong but, should the code be adding `KAFKA_OFFSET_RETENTION` to the timestamp of the last committed offset rather than subtracting?

**Comment by weeco** [comment]
Hey @frenayj ,
first of all I'm very sorry for responding so late, your issue slipped through my mails apparently.

Looking at the code I absolutely agree with you, it should be added and not subtracted. This might be a copy paste mistake. I just started writing on Kafka Minion v2 and I'll keep that in mind and fix that as well. Thanks for pointing it out

**Comment by weeco** [comment]
Fixed in v2
