### ISSUE TITLE
v2 breaks startup: failed to setup kafka service

### ISSUE THREAD

**Issue by ginkel** [cloudhut/kminion#70]
Hi there,

we have deployed K(afka) Minion from `quay.io/google-cloud-tools/kafka-minion:latest`. Since today's `v2` (?) update the service fails to start emitting the following logs before it exits:

```
{"level":"info","ts":1613416401.829281,"caller":"app/config.go:63","msg":"the env variable 'CONFIG_FILEPATH' is not set, therefore no YAML config will be loaded"}
{"level":"info","ts":"2021-02-15T19:13:21.829Z","msg":"started kminion","version":""}
{"level":"fatal","ts":"2021-02-15T19:13:21.829Z","msg":"failed to setup kafka service","error":"failed to create kafka Client: unable to parse addr:port in \"1.2.3.1:9092,1.2.3.2:9092,1.2.3.3:9092\""}
```

The list of Kafka brokers is supplied via an env variable:

```
KAFKA_BROKERS=1.2.3.1:9092,1.2.3.2:9092,1.2.3.3:9092
```

Thanks for looking into this,
Thilo

**Comment by weeco** [comment]
Hey Thilo,
that was quick 🚀 . The documentation isn't even ready yet :P.

I'm able to reproduce this and have submitted in issue here: https://github.com/knadh/koanf/issues/58 . The author is very responsive so I hope we can sort this out quickly. Sorry for that.

PS: Docker images go to https://quay.io/repository/cloudhut/kminion?tab=tags from now on :-).

**Comment by weeco** [comment]
Just pushed a fix for this. It will just look for `,` separated strings and return a string slice in that case. Not an ideal solution imho, but should be fine for now.
