### ISSUE TITLE
How to handle readiness and liveness probes in v2

### ISSUE THREAD

**Issue by frenayj** [cloudhut/kminion#71]
It seems like the readiness and liveness probes http handlers have been removed in v2.
What's the recommended way to manage this probes now?

**Comment by weeco** [comment]
Hi @frenayj , yes that's correct. KMinion is supposed to exit with an error code in case there are issues. The http server should becom available within a second. Therefore I think a readiness probe or liveness probe is not required. But maybe I'm missing a good argument why one would still want to have a probe? If so what's the usecase and what should the probe test against?

**Comment by weeco** [comment]
A readiness probe should definetely be added for those that use scrapingMode = offsetsTopic . It takes a bit until kminion is ready to report the metrics and therefore a readiness probe for rolling updates and ha setups is definetely important.

**Comment by weeco** [comment]
Readiness probe has been added, hence closing this issue.
