### ISSUE TITLE
Grafana dashboards v2

### ISSUE THREAD

**Issue by m3du54** [cloudhut/kminion#73]
Is it possible to share Grafana dashboards for V2? It seems that labeling for Prometheus is a lot different than v1.

**Comment by weeco** [comment]
Absolutely! I'll try to upload the Dashboard JSONs today or tomorrow. Sorry for teasing them in the readme without linking them, I didn't expect anyone to notice it so quickly.

**Comment by weeco** [comment]
Uploaded and linked in the Readme :-)
