### ISSUE TITLE
Service monitor helm chart typo

### ISSUE THREAD

**Issue by ianau74** [cloudhut/kminion#77]
I'm not able to submit a PR here, but I've fixed it in my local branch.

The helm chart for kminion fails when I set:
serviceMonitor.create: true

On line https://github.com/cloudhut/kminion/blob/master/charts/kminion/templates/servicemonitor.yaml#L14 it should be:
{{- include "kminion.labels" . | nindent 6}}
not
{{- include "kminion.labels" . | nindent 4}}

**Comment by weeco** [comment]
Hey @ianau74 ,
thanks for submitting the issue. I'm curious, is there a specific reason why you can't submit a PR? I think there aren't any permissions I could configure which would disallow others to submit a PR from their local fork, unless I'd disable PRs.

Anyways I fixed it in https://github.com/cloudhut/kminion/commit/49df52baaaaac11e1b0828e62a752085cba024f5 and will also trigger a patch release now
