### ISSUE TITLE
Errors in reference configuration

### ISSUE THREAD

**Issue by trietsch** [cloudhut/kminion#78]
I just tried setting up Kafka Minion, however, [the reference configuration](https://github.com/cloudhut/kminion/blob/master/docs/reference-config.yaml) is not working out of the box. Errors that I've seen so far:

- `invalid consumer group granularity 'partitions' specified. Valid modes are 'topic' or 'partition'`
- `1 error(s) decoding:\n\n* 'exporter' has invalid keys: path`

If I find more errors, I'll update this issue.

**Comment by weeco** [comment]
@trietsch Thanks, I fixed that with https://github.com/cloudhut/kminion/commit/4f4b8c5f2d3fe7c5a4277558fbc9157a0f7273b5

**Comment by trietsch** [comment]
I didn't find other issues than these btw. Feel free to close the issue.
