### ISSUE TITLE
kerberos error

### ISSUE THREAD

**Issue by wuzhix** [cloudhut/kminion#89]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xa3e65c]

goroutine 26 [running]:
github.com/jcmturner/gokrb5/v8/client.(*Client).IsConfigured(0x0, 0xc00028c200, 0x0, 0x0)
	C:/Users/360/go/pkg/mod/github.com/jcmturner/gokrb5/v8@v8.4.2/client/client.go:140 +0x5c
github.com/twmb/franz-go/pkg/sasl/kerberos.k.Authenticate(0xc00025a6f0, 0x1114b10, 0xc000238940, 0xc000250a00, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	C:/Users/360/go/pkg/mod/github.com/twmb/franz-go@v0.6.12/pkg/sasl/kerberos/kerberos.go:72 +0x274
github.com/twmb/franz-go/pkg/kgo.(*brokerCxn).doSasl(0xc000257e00, 0x0, 0x0, 0x0)
	C:/Users/360/go/pkg/mod/github.com/twmb/franz-go@v0.6.12/pkg/kgo/broker.go:685 +0x111
github.com/twmb/franz-go/pkg/kgo.(*brokerCxn).sasl(0xc000257e00, 0x0, 0x0)
	C:/Users/360/go/pkg/mod/github.com/twmb/franz-go@v0.6.12/pkg/kgo/broker.go:681 +0xe0d
github.com/twmb/franz-go/pkg/kgo.(*brokerCxn).init(0xc000257e00, 0xc000257e00, 0x0, 0x0)
	C:/Users/360/go/pkg/mod/github.com/twmb/franz-go@v0.6.12/pkg/kgo/broker.go:545 +0x3c9
github.com/twmb/franz-go/pkg/kgo.(*broker).loadConnection(0xc0001325a0, 0x1114b10, 0xc000238a80, 0x3, 0x0, 0x0, 0x0)
	C:/Users/360/go/pkg/mod/github.com/twmb/franz-go@v0.6.12/pkg/kgo/broker.go:402 +0x3dc
github.com/twmb/franz-go/pkg/kgo.(*broker).handleReqs(0xc0001325a0)
	C:/Users/360/go/pkg/mod/github.com/twmb/franz-go@v0.6.12/pkg/kgo/broker.go:232 +0x1dc
created by github.com/twmb/franz-go/pkg/kgo.(*Client).newBroker
	C:/Users/360/go/pkg/mod/github.com/twmb/franz-go@v0.6.12/pkg/kgo/broker.go:152 +0x22f

**Comment by weeco** [comment]
@wuzhix Can you paste what your config looks like? Password can obviously be redacted. It looks like the `Credentials` struct in the kerberos lib is nil. I'm not sure why this would happen (and that should be validated anyways), but I assume that the input into that lib may be invalid.

**Comment by wuzhix** [comment]
@weeco 
#####################################################################################
# This file documents all the available config options and it's default values.
#
# All config options can be configured via environment variables as well.
# If you specify both the env variable and yaml option for the same configuration
# the environment variable will take precedence. If you want to use a YAML config
# file, specify the path to the config file by setting the env variable
# CONFIG_FILEPATH.
#
# The env variable name is auto generated by upper casing everything and adding
# an underscore for each indentation/level. Some examples:
# kafka.rackId => KAFKA_RACKID
# kafka.tls.caFilepath => KAFKA_TLS_CAFILEPATH
# minion.consumerGroups.allowedGroups => MINION_CONSUMERGROUPS_ALLOWEDGROUPS
#
# Env variables that expect array values can be provided by separting them using
# a comma: KAFKA_BROKERS = "broker1:9092,broker2:9092,broker3:9092"
#####################################################################################
kafka:
  brokers: ["hdp83.bigdata.cn:9092","hdp84.bigdata.cn:9092"]
  clientId: "kminion"
  rackId: ""
  tls:
    enabled: false
    caFilepath: ""
    certFilepath: ""
    keyFilepath: ""
    passphrase: ""
    insecureSkipTlsVerify: false
  sasl:
    # Whether or not SASL authentication will be used for authentication
    enabled: true
    # Username to use for PLAIN or SCRAM mechanism
    username: ""
    # Password to use for PLAIN or SCRAM mechanism
    password: ""
    # Mechanism to use for SASL Authentication. Valid values are PLAIN, SCRAM-SHA-256, SCRAM-SHA-512, GSSAPI
    mechanism: "GSSAPI"
    # GSSAPI / Kerberos config properties
    gssapi:
      authType: "kerberos"
      keyTabPath: "D:/code/kminion-master/security.keytab"
      kerberosConfigPath: "D:/code/kminion-master/krb5.conf"
      serviceName: "kafka"
      username: "security"
      password: ""
      realm: "ZZYC.COM"

minion:
  consumerGroups:
    # Enabled specifies whether consumer groups shall be scraped and exported or not.
    enabled: true
    # Mode specifies whether we export consumer group offsets using the Admin API or by consuming the internal
    # __consumer_offsets topic. Both modes have their advantages and disadvantages.
    scrapeMode: adminApi # Valid values: adminApi, offsetsTopic
    # Granularity can be per topic or per partition. If you want to reduce the number of exported metric series and
    # you aren't interested in per partition lags you could choose "topic" where all partition lags will be summed
    # and only topic lags will be exported.
    granularity: partition
    # AllowedGroups are regex strings of group ids that shall be exported
    # You can specify allowed groups by providing literals like "my-consumergroup-name" or by providing regex expressions
    # like "/internal-.*/".
    allowedGroups: []
    # IgnoredGroups are regex strings of group ids that shall be ignored/skipped when exporting metrics. Ignored groups
    # take precedence over allowed groups.
    ignoredGroups: []
  topics:
    # Granularity can be per topic or per partition. If you want to reduce the number of exported metric series and
    # you aren't interested in per partition metrics you could choose "topic".
    granularity: partition
    # AllowedTopics are regex strings of topic names whose topic metrics that shall be exported.
    # You can specify allowed topics by providing literals like "my-topic-name" or by providing regex expressions
    # like "/internal-.*/".
    allowedTopics: []

    # IgnoredTopics are regex strings of topic names that shall be ignored/skipped when exporting metrics. Ignored topics
    # take precedence over allowed topics.
    ignoredTopics: []
  logDirs:
    # Enabled specifies whether log dirs shall be scraped and exported or not. This should be disabled for clusters prior
    # to version 1.0.0 as describing log dirs was not supported back then.
    enabled: true

exporter:
  # Namespace is the prefix for all exported Prometheus metrics
  namespace: "kminion"
  # Host that shall be used to bind the HTTP server on
  host: ""
  # Port that shall be used to bind the HTTP server on
  port: 8080

logger:
  # Level is a logging priority. Higher levels are more important. Valid values are: debug, info, warn, error, fatal, panic
  level: info

**Comment by wuzhix** [comment]
@weeco 
#####################################################################################
# This file documents all the available config options and it's default values.
#
# All config options can be configured via environment variables as well.
# If you specify both the env variable and yaml option for the same configuration
# the environment variable will take precedence. If you want to use a YAML config
# file, specify the path to the config file by setting the env variable
# CONFIG_FILEPATH.
#
# The env variable name is auto generated by upper casing everything and adding
# an underscore for each indentation/level. Some examples:
# kafka.rackId => KAFKA_RACKID
# kafka.tls.caFilepath => KAFKA_TLS_CAFILEPATH
# minion.consumerGroups.allowedGroups => MINION_CONSUMERGROUPS_ALLOWEDGROUPS
#
# Env variables that expect array values can be provided by separting them using
# a comma: KAFKA_BROKERS = "broker1:9092,broker2:9092,broker3:9092"
#####################################################################################
kafka:
  brokers: ["hdp83.bigdata.cn:9092","hdp84.bigdata.cn:9092"]
  clientId: "kminion"
  rackId: ""
  tls:
    enabled: false
    caFilepath: ""
    certFilepath: ""
    keyFilepath: ""
    passphrase: ""
    insecureSkipTlsVerify: false
  sasl:
    # Whether or not SASL authentication will be used for authentication
    enabled: true
    # Username to use for PLAIN or SCRAM mechanism
    username: ""
    # Password to use for PLAIN or SCRAM mechanism
    password: ""
    # Mechanism to use for SASL Authentication. Valid values are PLAIN, SCRAM-SHA-256, SCRAM-SHA-512, GSSAPI
    mechanism: "GSSAPI"
    # GSSAPI / Kerberos config properties
    gssapi:
      authType: "kerberos"
      keyTabPath: "D:/code/kminion-master/security.keytab"
      kerberosConfigPath: "D:/code/kminion-master/krb5.conf"
      serviceName: "kafka"
      username: "security"
      password: ""
      realm: "ZZYC.COM"

minion:
  consumerGroups:
    # Enabled specifies whether consumer groups shall be scraped and exported or not.
    enabled: true
    # Mode specifies whether we export consumer group offsets using the Admin API or by consuming the internal
    # __consumer_offsets topic. Both modes have their advantages and disadvantages.
    scrapeMode: adminApi # Valid values: adminApi, offsetsTopic
    # Granularity can be per topic or per partition. If you want to reduce the number of exported metric series and
    # you aren't interested in per partition lags you could choose "topic" where all partition lags will be summed
    # and only topic lags will be exported.
    granularity: partition
    # AllowedGroups are regex strings of group ids that shall be exported
    # You can specify allowed groups by providing literals like "my-consumergroup-name" or by providing regex expressions
    # like "/internal-.*/".
    allowedGroups: []
    # IgnoredGroups are regex strings of group ids that shall be ignored/skipped when exporting metrics. Ignored groups
    # take precedence over allowed groups.
    ignoredGroups: []
  topics:
    # Granularity can be per topic or per partition. If you want to reduce the number of exported metric series and
    # you aren't interested in per partition metrics you could choose "topic".
    granularity: partition
    # AllowedTopics are regex strings of topic names whose topic metrics that shall be exported.
    # You can specify allowed topics by providing literals like "my-topic-name" or by providing regex expressions
    # like "/internal-.*/".
    allowedTopics: []

    # IgnoredTopics are regex strings of topic names that shall be ignored/skipped when exporting metrics. Ignored topics
    # take precedence over allowed topics.
    ignoredTopics: []
  logDirs:
    # Enabled specifies whether log dirs shall be scraped and exported or not. This should be disabled for clusters prior
    # to version 1.0.0 as describing log dirs was not supported back then.
    enabled: true

exporter:
  # Namespace is the prefix for all exported Prometheus metrics
  namespace: "kminion"
  # Host that shall be used to bind the HTTP server on
  host: ""
  # Port that shall be used to bind the HTTP server on
  port: 8080

logger:
  # Level is a logging priority. Higher levels are more important. Valid values are: debug, info, warn, error, fatal, panic
  level: info

**Comment by wuzhix** [comment]
@weeco 
![1](https://user-images.githubusercontent.com/7930936/118208747-e599f400-b499-11eb-9668-0ed9baa7b2b2.png)
![2](https://user-images.githubusercontent.com/7930936/118208756-e894e480-b499-11eb-8af6-1bf0e4d706f6.png)

**Comment by weeco** [comment]
@wuzhix Use gssapi.authType = "KEYTAB_AUTH" and not "kerberos".
