### ISSUE TITLE
Any option to get kafka_minion_topic_subscribed_groups_count metrics

### ISSUE THREAD

**Issue by kaushal1562** [cloudhut/kminion#92]
Any option to get kafka_minion_topic_subscribed_groups_count metrics in new version. It was available in old version but not in new.

**Comment by weeco** [comment]
Yes you can just use something like `sum(kminion_kafka_consumer_group_topic_lag{topic_name="$topic"})`

**Comment by kaushal1562** [comment]
@weeco  Nope , this dosent give correct result.

**Comment by weeco** [comment]
@kaushal1562 Can you check why is that? Take a look at the individual series. Are you running 2 instances of KMinion by any chance?

If you use the prebuilt Grafana dashboard you should see the results of that query in the Dashboard "KMinion Topic" - Panel: "Subscribed Consumer Groups" as well.

**Comment by kaushal1562** [comment]
@weeco 
I am running only 1 instance for new version and 1 instance for old version so that I can compare the result and found difference in the result of sum(kminion_kafka_consumer_group_topic_lag{topic_name="$topic"}) and kafka_minion_topic_subscribed_groups_count .

kafka_minion_topic_subscribed_groups_count gives result - 3
sum(kminion_kafka_consumer_group_topic_lag{topic_name="$topic"}) -- This gives 0

**Comment by weeco** [comment]
Just to make sure: Have you replaced `$topic` with the actual topic name that you want to know the subscribed consumer group count for?

If yes: Please check the results of that metric series (without label filter) and see what is wrong there.

**Comment by kaushal1562** [comment]
yes, i am checking for only single topic data. I have replaced it with actual topic name,

**Comment by kaushal1562** [comment]
I have tested with multiple topic and  sum(kminion_kafka_consumer_group_topic_lag{topic_name="$topic"}) is giving only count of lag. If there is no lag , count shows 0

**Comment by weeco** [comment]
> I have tested with multiple topic and sum(kminion_kafka_consumer_group_topic_lag{topic_name="$topic"}) is giving only count of lag. If there is no lag , count shows 0

Ah of course, just use `count()` instead of `sum()`

**Comment by kaushal1562** [comment]
ohh yes...thank you..issue solved
