### ISSUE TITLE
'unable to initialize sasl' exception when connects kerberized Kafka.

### ISSUE THREAD

**Issue by wangqinghuan** [cloudhut/kminion#94]
config.yaml:
> kafka:
>   brokers: [172.16.1.102:21007]
>   clientId: "kminion"
>   rackId: ""
>   tls:
>     enabled: false
>     caFilepath: ""
>     certFilepath: ""
>     keyFilepath: ""
>     passphrase: ""
>     insecureSkipTlsVerify: false
>   sasl:
>     # Whether or not SASL authentication will be used for authentication
>     enabled: true
>     # Username to use for PLAIN or SCRAM mechanism
>     username: ""
>     # Password to use for PLAIN or SCRAM mechanism
>     password: ""
>     # Mechanism to use for SASL Authentication. Valid values are PLAIN, SCRAM-SHA-256, SCRAM-SHA-512, GSSAPI
>     mechanism: "GSSAPI"
>     # GSSAPI / Kerberos config properties
>     gssapi:
>       authType: "KEYTAB_AUTH"
>       keyTabPath: "C:\\user.keytab"
>       kerberosConfigPath: "C:\\krb5.conf"
>       serviceName: "kafka"
>       username: "qdgakk"
>       password: ""
>       realm: "BOTECH.COM"

Debug Info:
> {"level":"info","ts":"2021-06-02T14:54:33.297+0800","msg":"started kminion","version":""}
> {"level":"info","ts":"2021-06-02T14:54:33.311+0800","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata","seed_brokers":"172.16.1.102:21007"}
> {"level":"debug","ts":"2021-06-02T14:54:33.311+0800","msg":"opening connection to broker","source":"kafka_client","addr":"172.16.1.102:21007","broker":-2147483648}
> {"level":"debug","ts":"2021-06-02T14:54:33.315+0800","msg":"kafka connection succeeded","source":"kafka_client_hooks","host":"172.16.1.102","dial_duration":0.0037961}
> {"level":"debug","ts":"2021-06-02T14:54:33.315+0800","msg":"connection opened to broker","source":"kafka_client","addr":"172.16.1.102:21007","broker":-2147483648}
> {"level":"debug","ts":"2021-06-02T14:54:33.316+0800","msg":"issuing api versions request","source":"kafka_client","broker":-2147483648,"version":3}
> {"level":"debug","ts":"2021-06-02T14:54:33.317+0800","msg":"wrote ApiVersions v3","source":"kafka_client","broker":-2147483648,"bytes_written":33,"write_wait":0,"time_to_write":0.0005889,"err":null}
> {"level":"debug","ts":"2021-06-02T14:54:33.319+0800","msg":"read ApiVersions v3","source":"kafka_client","broker":-2147483648,"bytes_read":14,"read_wait":0,"time_to_read":0.0020606,"err":null}
> {"level":"debug","ts":"2021-06-02T14:54:33.319+0800","msg":"kafka does not know our ApiVersions version, downgrading to version 0 and retrying","source":"kafka_client","broker":-2147483648}
> {"level":"debug","ts":"2021-06-02T14:54:33.319+0800","msg":"issuing api versions request","source":"kafka_client","broker":-2147483648,"version":0}
> {"level":"debug","ts":"2021-06-02T14:54:33.319+0800","msg":"wrote ApiVersions v0","source":"kafka_client","broker":-2147483648,"bytes_written":21,"write_wait":0,"time_to_write":0,"err":null}
> {"level":"debug","ts":"2021-06-02T14:54:33.325+0800","msg":"read ApiVersions v0","source":"kafka_client","broker":-2147483648,"bytes_read":218,"read_wait":0,"time_to_read":0.0050713,"err":null}
> {"level":"debug","ts":"2021-06-02T14:54:33.328+0800","msg":"beginning sasl authentication","source":"kafka_client","broker":-2147483648,"mechanism":"GSSAPI","authenticate":false}
> {"level":"debug","ts":"2021-06-02T14:54:33.438+0800","msg":"issuing raw sasl authenticate","source":"kafka_client","broker":-2147483648,"step":0}
> {"level":"error","ts":"2021-06-02T14:54:33.443+0800","msg":"unable to initialize sasl","source":"kafka_client","broker":-2147483648,"err":"EOF"}
> {"level":"debug","ts":"2021-06-02T14:54:33.443+0800","msg":"connection initialization failed","source":"kafka_client","addr":"172.16.1.102:21007","broker":-2147483648,"err":"EOF"}
> {"level":"debug","ts":"2021-06-02T14:54:33.444+0800","msg":"kafka broker disconnected","source":"kafka_client_hooks","host":"172.16.1.102"}
> {"level":"debug","ts":"2021-06-02T14:54:33.530+0800","msg":"opening connection to broker","source":"kafka_client","addr":"172.16.1.102:21007","broker":-2147483648}
> {"level":"debug","ts":"2021-06-02T14:54:33.534+0800","msg":"kafka connection succeeded","source":"kafka_client_hooks","host":"172.16.1.102","dial_duration":0.0025582}
> {"level":"debug","ts":"2021-06-02T14:54:33.534+0800","msg":"connection opened to broker","source":"kafka_client","addr":"172.16.1.102:21007","broker":-2147483648}
> {"level":"debug","ts":"2021-06-02T14:54:33.536+0800","msg":"issuing api versions request","source":"kafka_client","broker":-2147483648,"version":3}
> {"level":"debug","ts":"2021-06-02T14:54:33.537+0800","msg":"wrote ApiVersions v3","source":"kafka_client","broker":-2147483648,"bytes_written":33,"write_wait":0,"time_to_write":0,"err":null}
> {"level":"debug","ts":"2021-06-02T14:54:33.541+0800","msg":"read ApiVersions v3","source":"kafka_client","broker":-2147483648,"bytes_read":14,"read_wait":0,"time_to_read":0.0041925,"err":null}
> {"level":"debug","ts":"2021-06-02T14:54:33.541+0800","msg":"kafka does not know our ApiVersions version, downgrading to version 0 and retrying","source":"kafka_client","broker":-2147483648}
> {"level":"debug","ts":"2021-06-02T14:54:33.541+0800","msg":"issuing api versions request","source":"kafka_client","broker":-2147483648,"version":0}
> {"level":"debug","ts":"2021-06-02T14:54:33.542+0800","msg":"wrote ApiVersions v0","source":"kafka_client","broker":-2147483648,"bytes_written":21,"write_wait":0,"time_to_write":0,"err":null}
> {"level":"debug","ts":"2021-06-02T14:54:33.545+0800","msg":"read ApiVersions v0","source":"kafka_client","broker":-2147483648,"bytes_read":218,"read_wait":0,"time_to_read":0.0020165,"err":null}
> {"level":"debug","ts":"2021-06-02T14:54:33.545+0800","msg":"beginning sasl authentication","source":"kafka_client","broker":-2147483648,"mechanism":"GSSAPI","authenticate":false}
> {"level":"debug","ts":"2021-06-02T14:54:33.545+0800","msg":"issuing raw sasl authenticate","source":"kafka_client","broker":-2147483648,"step":0}
> {"level":"error","ts":"2021-06-02T14:54:33.552+0800","msg":"unable to initialize sasl","source":"kafka_client","broker":-2147483648,"err":"EOF"}
> {"level":"debug","ts":"2021-06-02T14:54:33.552+0800","msg":"connection initialization failed","source":"kafka_client","addr":"172.16.1.102:21007","broker":-2147483648,"err":"EOF"}
> {"level":"debug","ts":"2021-06-02T14:54:33.552+0800","msg":"kafka broker disconnected","source":"kafka_client_hooks","host":"172.16.1.102"}
> {"level":"info","ts":"2021-06-02T14:54:33.765+0800","msg":"received a signal, going to shut down KMinion"}
> {"level":"debug","ts":"2021-06-02T14:54:33.765+0800","msg":"opening connection to broker","source":"kafka_client","addr":"172.16.1.102:21007","broker":-2147483648}
> {"level":"debug","ts":"2021-06-02T14:54:33.767+0800","msg":"kafka connection failed","source":"kafka_client_hooks","broker_host":"172.16.1.102","error":"dial tcp 172.16.1.102:21007: operation was canceled"}
> {"level":"warn","ts":"2021-06-02T14:54:33.768+0800","msg":"unable to open connection to broker","source":"kafka_client","addr":"172.16.1.102:21007","broker":-2147483648,"err":"dial tcp 172.16.1.102:21007: operation was canceled"}
> {"level":"fatal","ts":"2021-06-02T14:54:33.771+0800","msg":"failed to test connectivity to Kafka cluster","error":"failed to request metadata: unable to dial: dial tcp 172.16.1.102:21007: operation was canceled"}

Do you know how I can avoid this exception? Appreciate

**Comment by weeco** [comment]
Hey @wangqinghuan , I noticed you created an issue in franz-go directly. I'll close this issue here and we'll track it in the franz-go repo instead.
